# Generated by Django 6.0.5 on 2026-05-29 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('categoria', models.CharField(help_text='Ej: Sub-15, Senior, Reserva', max_length=50)),
                ('posicion', models.CharField(help_text='Ej: Delantero, Central, Portero', max_length=50)),
                ('foto_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el jugador sigue activo en el equipo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
