# Generated by Django 6.0.5 on 2026-05-29 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_jugador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rival', models.CharField(max_length=150)),
                ('fecha', models.DateTimeField()),
                ('lugar', models.CharField(max_length=150)),
                ('resultado_final', models.CharField(blank=True, help_text='Ej: 3-1', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Permite cancelar o suspender lógicamente el partido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
