# Generated by Django 6.0.5 on 2026-05-29 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_partido'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos_jugados', models.PositiveIntegerField(default=0)),
                ('goles', models.PositiveIntegerField(default=0)),
                ('asistencias', models.PositiveIntegerField(default=0)),
                ('tarjetas_amarillas', models.PositiveIntegerField(default=0)),
                ('tarjeta_roja', models.BooleanField(default=False)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_partidos', to='gestion.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='gestion.partido')),
            ],
            options={
                'verbose_name': 'Evento de Partido',
                'verbose_name_plural': 'Eventos de Partidos',
                'unique_together': {('partido', 'jugador')},
            },
        ),
    ]
