# Generated by Django 6.0.5 on 2026-05-29 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_eventopartido'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionRendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura_cm', models.PositiveIntegerField()),
                ('velocidad_seg', models.DecimalField(decimal_places=2, help_text='Tiempo en sprint de 100m o similar', max_digits=4)),
                ('calificacion_tecnica', models.PositiveIntegerField(help_text='Escala 1-100')),
                ('notas_comentario', models.TextField(blank=True, default='')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='gestion.jugador')),
            ],
            options={
                'verbose_name': 'Evaluación de Rendimiento',
                'verbose_name_plural': 'Evaluaciones de Rendimiento',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
